Master filter
CMU-cabot/cabot_design pull request #1
Opened 2020-05-18 14:51 UTC by arunumd

2020-05-18 15:03 UTC, daisukes requested changes

2020-05-18 15:03 UTC, daisukes commented on README.md
> +# Cabot_design
change here to "Cabot Design" and could you add one sentence about this repo?

2020-05-18 15:03 UTC, daisukes commented on README.md
> +# Cabot_design
Also we need to add a link to handle Arduino code repo (also need to make it public)

2020-05-18 15:13 UTC, arunumd commented on README.md
> +# Cabot_design
Please check now

2020-05-20 18:00 UTC, merged

2020-05-20 18:00 UTC, daisukes commented
close #2